-
  name:  'ATOM'
  uriPattern: '{node}.atom'
  defaults:
    '@package': 'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    '@format': 'atom'
  routeParts:
    'node':
      handler: 'TYPO3\Neos\Routing\FrontendNodeRoutePartHandler'
