-
  name:  'ATOM'
  uriPattern: '{node}.atom'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    '@format': 'atom'
  routeParts:
    'node':
      handler: 'Neos\Neos\Routing\FrontendNodeRoutePartHandler'

-
  name:  'AMP blog entries'
  uriPattern: 'amplify/{node}.html'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    '@format': 'html'
    '--blog-amplify': true
  routeParts:
    'node':
      handler: 'Neos\Neos\Routing\FrontendNodeRoutePartHandler'

-
  name: 'Blog paginate'
  uriPattern: '{node}/browse/{--blog-pagination.currentPage}.html'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    '@format': 'html'
    '--blog-pagination':
      '@package': ''
      '@subpackage': ''
      '@controller': ''
      '@action': 'index'
      'currentPage': '1'
  routeParts:
    node:
      handler: Neos\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: TRUE
