TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Shel.Blog': TRUE

Shel:
  Blog:
    dateFormat: 'm/d/Y'
    socialButtons:
      enabled: FALSE
      twitterId: ''
      flattrId: ''
    disqus:
      shortname: ''
    pagination:
      itemsPerPage: 5
      maximumNumberOfLinks: 10
