Shel:
  Blog:
    cldrFormat: null
    localeFormatLength: 'long'
    showAuthor: true
    atomImageMaxWidth: 400
    socialButtons:
      enabled: false
      twitterId: ''
      flattrId: ''
    disqus:
      enabled: false
      shortname: ''
    pagination:
      itemsPerPage: 5
      maximumNumberOfLinks: 10

Neos:
  Flow:
    mvc:
      routes:
        Shel.Blog:
          position: 'before Neos.Neos'
  Neos:
    userInterface:
      translation:
        autoInclude:
          Shel.Blog:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Shel.Blog: true
  Fusion:
    defaultContext:
      'Shel.Blog.Asset': 'Shel\Blog\Fusion\Helper\AssetHelper'
