TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Shel.Blog': true

    userInterface:
      translation:
        autoInclude:
          'Shel.Blog': ['NodeTypes/*']

  TypoScript:
    defaultContext:
      'Shel.Blog.Asset': 'Shel\Blog\TypoScript\Helper\AssetHelper'

Shel:
  Blog:
    dateFormat: 'M d, Y'
    atomImageMaxWidth: 400
    socialButtons:
      enabled: false
      twitterId: ''
      flattrId: ''
    disqus:
      enabled: false
      shortname: ''
    pagination:
      itemsPerPage: 5
      maximumNumberOfLinks: 10
