Neos:
  Flow:
    mvc:
      routes:
        Shel.Blog:
          position: 'before Neos.Neos'
          variables:
            # Set this to an empty string if you prefer URLs without the ".html" suffix
            'defaultUriSuffix': '.html'
  Neos:
    userInterface:
      translation:
        autoInclude:
          Shel.Blog:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Shel.Blog: true
  Fusion:
    defaultContext:
      'Shel.Blog.Asset': 'Shel\Blog\Fusion\Helper\AssetHelper'
