
Shel:
  Blog:
    dateFormat: 'M d, Y'
    socialButtons:
      enabled: false
      twitterId: ''
      flattrId: ''
    disqus:
      enabled: false
      shortname: ''
    pagination:
      itemsPerPage: 5
      maximumNumberOfLinks: 10
Neos:
  Neos:
    typoScript:
      autoInclude:
        Shel.Blog: true
    userInterface:
      translation:
        autoInclude:
          Shel.Blog:
            - 'NodeTypes/*'
