TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Shel.Blog': TRUE

Shel:
  Blog:
    socialButtons:
      enabled: FALSE
      twitterId: ''
      flattrId: ''
    disqus:
      shortname: ''
